# basic options
title: Blog
author: Nana-Addo
email: nanaaddo10@gmail.com
description: Please Send Help!!!
twitter_username: 
github_username:  nana-addo

# Build settings
markdown: kramdown
theme: minima
